# Generated by Django 5.2 on 2025-04-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_context', models.TextField()),
                ('page_number', models.IntegerField()),
                ('citation_date', models.DateField(auto_now_add=True)),
                ('impact_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cited_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_received', to='research_papers.researchpaper')),
                ('citing_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_made', to='research_papers.researchpaper')),
            ],
        ),
    ]
