# Generated by Django 5.2 on 2025-04-12 01:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_vehiculo', models.CharField(choices=[('CAMION', 'Camión'), ('FURGONETA', 'Furgoneta'), ('TRAILER', 'Tráiler'), ('OTRO', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=50)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('kilometraje', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportes', to='conductores.conductor')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
