# Generated by Django 5.2 on 2025-04-12 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('tipo_licencia', models.CharField(max_length=20)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('años_experiencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'Vacaciones'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('direccion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
